SAFFIER_DISCOVER_APP = "SAFFIER_DEFAULT_APP"
DEFAULT_TEMPLATE_NAME = "default"
APP_PARAMETER = "--app"
HELP_PARAMETER = "--help"
DISCOVERY_FILES = ["application.py", "app.py", "main.py"]
DISCOVERY_FUNCTIONS = ["get_application", "get_app"]
DISCOVERY_PRELOADS = ["application", "app", "main", "asgi"]
SAFFIER_DB = "_saffier_db"
SAFFIER_EXTRA = "_saffier_extra"
COMMANDS_WITHOUT_APP = ["list-templates", "inspectdb", "init"]
IGNORE_COMMANDS = COMMANDS_WITHOUT_APP
