SAFFIER_DISCOVER_APP = "SAFFIER_DEFAULT_APP"
DEFAULT_TEMPLATE_NAME = "default"
APP_PARAMETER = "--app"
HELP_PARAMETER = "--help"
DISCOVERY_FILES = ["application.py", "app.py", "main.py"]
DISCOVERY_FUNCTIONS = ["get_application", "get_app"]
SAFFIER_DB = "_saffier_db"
EXCLUDED_COMMANDS = ["list-templates"]
IGNORE_COMMANDS = ["list-templates"]
