#!/bin/sh -e

export PREFIX=""
if [ "$VIRTUAL_ENV" != '' ]; then
    export PREFIX="$VIRTUAL_ENV/bin/"
elif [ -d 'venv' ] ; then
    export PREFIX="venv/bin/"
fi
export SOURCE_FILES="saffier tests"
export EXCLUDE=__init__.py
export MAIN="saffier"

${PREFIX}ty check $MAIN
${PREFIX}ruff check $SOURCE_FILES --line-length 99
${PREFIX}ruff format $SOURCE_FILES --check
