#!/bin/sh -e

export PREFIX=""
if [ "$VIRTUAL_ENV" != '' ]; then
    export PREFIX="$VIRTUAL_ENV/bin/"
elif [ -d 'venv' ] ; then
    export PREFIX="venv/bin/"
fi
export SOURCE_FILES="saffier tests docs_src"
export EXCLUDE=__init__.py
export MAIN="saffier"

set -x
./scripts/sync-version
${PREFIX}mypy $MAIN
${PREFIX}ruff $SOURCE_FILES --line-length 99
${PREFIX}black --check --diff $SOURCE_FILES --line-length 99
${PREFIX}isort --check --diff --project=saffier $SOURCE_FILES --line-length 99
