#!/bin/sh -e

if [ -d 'dist' ] ; then
    rm -r dist
fi
if [ -d 'site' ] ; then
    rm -r site
fi
if [ -d 'docs-generated' ] ; then
    rm -r docs-generated
fi
if [ -d '.cache' ] ; then
    rm -r .cache
fi
if [ -d 'htmlcov' ] ; then
    rm -r htmlcov
fi
if [ -d 'saffier.egg-info' ] ; then
    rm -r saffier.egg-info
fi
if [ -d '.hypothesis' ] ; then
    rm -r .hypothesis
fi
if [ -d '.mypy_cache' ] ; then
    rm -r .mypy_cache
fi
if [ -d '.pytest_cache' ] ; then
    rm -r .pytest_cache
fi
if [ -d '.ruff_cache' ] ; then
    rm -r .ruff_cache
fi
