#!/bin/sh -e

export PREFIX=""
if [ "$VIRTUAL_ENV" != '' ]; then
    export PREFIX="$VIRTUAL_ENV/bin/"
elif [ -d 'venv' ] ; then
    export PREFIX="venv/bin/"
fi
export SOURCE_FILES="saffier tests docs_src"
export EXCLUDE=__init__.py

set -x

${PREFIX}ruff $SOURCE_FILES --fix --line-length 99
${PREFIX}black $SOURCE_FILES --check --line-length 99
${PREFIX}isort $SOURCE_FILES --project=saffier --line-length 99