---
name: Test Suite

on:
  push:
    branches:
      - "**"
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "0 0 * * *"

jobs:
  tests:
    name: "Python ${{ matrix.python-version }}"
    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]

    services:

      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: saffier
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      postgres_alt:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: saffier_alt
        ports:
          - 5433:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: "actions/checkout@v5"
      - uses: "actions/setup-python@v6"
        with:
          python-version: "${{ matrix.python-version }}"
          allow-prereleases: true
      - uses: actions/cache@v4
        id: cache
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ runner.os }}-python-${{ env.pythonLocation }}-${{ hashFiles('pyproject.toml') }}-test-v03
      - name: "Install dependencies"
        if: steps.cache.outputs.cache-hit != 'true'
        run: "scripts/install"
      - name: "Install Hatch"
        run: "python -m pip install --upgrade pip hatch"
      - name: "Run lint checks"
        run: "python -m hatch run python -m ruff check saffier tests docs_src --line-length 99"
      - name: "Run type checks (Ty)"
        run: "python -m hatch run test:check_types"
      - name: "Run tests"
        env:
          TEST_DATABASE_URL: "postgresql+asyncpg://postgres:postgres@localhost:5432/saffier"
          TEST_DATABASE_ALTERNATIVE_URL: "postgresql+asyncpg://postgres:postgres@localhost:5433/saffier_alt"
        run: "hatch run test:test"
